package com.simon.cloud.leaf.api.entity;

import java.util.Date;

public class AdminStore {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_store.id
     *
     * @mbg.generated Thu Apr 18 10:47:46 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_store.store_name
     *
     * @mbg.generated Thu Apr 18 10:47:46 CST 2019
     */
    private String storeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_store.store_address
     *
     * @mbg.generated Thu Apr 18 10:47:46 CST 2019
     */
    private String storeAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_store.create_time
     *
     * @mbg.generated Thu Apr 18 10:47:46 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_store.update_time
     *
     * @mbg.generated Thu Apr 18 10:47:46 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_store.province
     *
     * @mbg.generated Thu Apr 18 10:47:46 CST 2019
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_store.city
     *
     * @mbg.generated Thu Apr 18 10:47:46 CST 2019
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_store.area
     *
     * @mbg.generated Thu Apr 18 10:47:46 CST 2019
     */
    private String area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_store.province_name
     *
     * @mbg.generated Thu Apr 18 10:47:46 CST 2019
     */
    private String provinceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_store.city_name
     *
     * @mbg.generated Thu Apr 18 10:47:46 CST 2019
     */
    private String cityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_store.area_name
     *
     * @mbg.generated Thu Apr 18 10:47:46 CST 2019
     */
    private String areaName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_store.store_logo
     *
     * @mbg.generated Thu Apr 18 10:47:46 CST 2019
     */
    private String storeLogo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_store.store_status
     *
     * @mbg.generated Thu Apr 18 10:47:46 CST 2019
     */
    private Integer storeStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_store.id
     *
     * @return the value of admin_store.id
     *
     * @mbg.generated Thu Apr 18 10:47:46 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_store.id
     *
     * @param id the value for admin_store.id
     *
     * @mbg.generated Thu Apr 18 10:47:46 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_store.store_name
     *
     * @return the value of admin_store.store_name
     *
     * @mbg.generated Thu Apr 18 10:47:46 CST 2019
     */
    public String getStoreName() {
        return storeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_store.store_name
     *
     * @param storeName the value for admin_store.store_name
     *
     * @mbg.generated Thu Apr 18 10:47:46 CST 2019
     */
    public void setStoreName(String storeName) {
        this.storeName = storeName == null ? null : storeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_store.store_address
     *
     * @return the value of admin_store.store_address
     *
     * @mbg.generated Thu Apr 18 10:47:46 CST 2019
     */
    public String getStoreAddress() {
        return storeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_store.store_address
     *
     * @param storeAddress the value for admin_store.store_address
     *
     * @mbg.generated Thu Apr 18 10:47:46 CST 2019
     */
    public void setStoreAddress(String storeAddress) {
        this.storeAddress = storeAddress == null ? null : storeAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_store.create_time
     *
     * @return the value of admin_store.create_time
     *
     * @mbg.generated Thu Apr 18 10:47:46 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_store.create_time
     *
     * @param createTime the value for admin_store.create_time
     *
     * @mbg.generated Thu Apr 18 10:47:46 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_store.update_time
     *
     * @return the value of admin_store.update_time
     *
     * @mbg.generated Thu Apr 18 10:47:46 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_store.update_time
     *
     * @param updateTime the value for admin_store.update_time
     *
     * @mbg.generated Thu Apr 18 10:47:46 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_store.province
     *
     * @return the value of admin_store.province
     *
     * @mbg.generated Thu Apr 18 10:47:46 CST 2019
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_store.province
     *
     * @param province the value for admin_store.province
     *
     * @mbg.generated Thu Apr 18 10:47:46 CST 2019
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_store.city
     *
     * @return the value of admin_store.city
     *
     * @mbg.generated Thu Apr 18 10:47:46 CST 2019
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_store.city
     *
     * @param city the value for admin_store.city
     *
     * @mbg.generated Thu Apr 18 10:47:46 CST 2019
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_store.area
     *
     * @return the value of admin_store.area
     *
     * @mbg.generated Thu Apr 18 10:47:46 CST 2019
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_store.area
     *
     * @param area the value for admin_store.area
     *
     * @mbg.generated Thu Apr 18 10:47:46 CST 2019
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_store.province_name
     *
     * @return the value of admin_store.province_name
     *
     * @mbg.generated Thu Apr 18 10:47:46 CST 2019
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_store.province_name
     *
     * @param provinceName the value for admin_store.province_name
     *
     * @mbg.generated Thu Apr 18 10:47:46 CST 2019
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName == null ? null : provinceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_store.city_name
     *
     * @return the value of admin_store.city_name
     *
     * @mbg.generated Thu Apr 18 10:47:46 CST 2019
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_store.city_name
     *
     * @param cityName the value for admin_store.city_name
     *
     * @mbg.generated Thu Apr 18 10:47:46 CST 2019
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_store.area_name
     *
     * @return the value of admin_store.area_name
     *
     * @mbg.generated Thu Apr 18 10:47:46 CST 2019
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_store.area_name
     *
     * @param areaName the value for admin_store.area_name
     *
     * @mbg.generated Thu Apr 18 10:47:46 CST 2019
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName == null ? null : areaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_store.store_logo
     *
     * @return the value of admin_store.store_logo
     *
     * @mbg.generated Thu Apr 18 10:47:46 CST 2019
     */
    public String getStoreLogo() {
        return storeLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_store.store_logo
     *
     * @param storeLogo the value for admin_store.store_logo
     *
     * @mbg.generated Thu Apr 18 10:47:46 CST 2019
     */
    public void setStoreLogo(String storeLogo) {
        this.storeLogo = storeLogo == null ? null : storeLogo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_store.store_status
     *
     * @return the value of admin_store.store_status
     *
     * @mbg.generated Thu Apr 18 10:47:46 CST 2019
     */
    public Integer getStoreStatus() {
        return storeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_store.store_status
     *
     * @param storeStatus the value for admin_store.store_status
     *
     * @mbg.generated Thu Apr 18 10:47:46 CST 2019
     */
    public void setStoreStatus(Integer storeStatus) {
        this.storeStatus = storeStatus;
    }
}