package com.simon.cloud.leaf.api.entity;

import org.hibernate.validator.constraints.NotBlank;

import java.util.Date;

public class AdminUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.id
     *
     * @mbg.generated Fri Mar 29 11:59:24 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.login_name
     *
     * @mbg.generated Fri Mar 29 11:59:24 CST 2019
     */
    @NotBlank
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.login_password
     *
     * @mbg.generated Fri Mar 29 11:59:24 CST 2019
     */
    @NotBlank
    private String loginPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.real_name
     *
     * @mbg.generated Fri Mar 29 11:59:24 CST 2019
     */
    private String realName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.nick_name
     *
     * @mbg.generated Fri Mar 29 11:59:24 CST 2019
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.img_url
     *
     * @mbg.generated Fri Mar 29 11:59:24 CST 2019
     */
    private String imgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.create_time
     *
     * @mbg.generated Fri Mar 29 11:59:24 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.update_time
     *
     * @mbg.generated Fri Mar 29 11:59:24 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.user_status
     *
     * @mbg.generated Fri Mar 29 11:59:24 CST 2019
     */
    private Integer userStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.user_phone
     *
     * @mbg.generated Fri Mar 29 11:59:24 CST 2019
     */
    @NotBlank
    private String userPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.user_email
     *
     * @mbg.generated Fri Mar 29 11:59:24 CST 2019
     */
    private String userEmail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.id
     *
     * @return the value of admin_user.id
     *
     * @mbg.generated Fri Mar 29 11:59:24 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.id
     *
     * @param id the value for admin_user.id
     *
     * @mbg.generated Fri Mar 29 11:59:24 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.login_name
     *
     * @return the value of admin_user.login_name
     *
     * @mbg.generated Fri Mar 29 11:59:24 CST 2019
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.login_name
     *
     * @param loginName the value for admin_user.login_name
     *
     * @mbg.generated Fri Mar 29 11:59:24 CST 2019
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.login_password
     *
     * @return the value of admin_user.login_password
     *
     * @mbg.generated Fri Mar 29 11:59:24 CST 2019
     */
    public String getLoginPassword() {
        return loginPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.login_password
     *
     * @param loginPassword the value for admin_user.login_password
     *
     * @mbg.generated Fri Mar 29 11:59:24 CST 2019
     */
    public void setLoginPassword(String loginPassword) {
        this.loginPassword = loginPassword == null ? null : loginPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.real_name
     *
     * @return the value of admin_user.real_name
     *
     * @mbg.generated Fri Mar 29 11:59:24 CST 2019
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.real_name
     *
     * @param realName the value for admin_user.real_name
     *
     * @mbg.generated Fri Mar 29 11:59:24 CST 2019
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.nick_name
     *
     * @return the value of admin_user.nick_name
     *
     * @mbg.generated Fri Mar 29 11:59:24 CST 2019
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.nick_name
     *
     * @param nickName the value for admin_user.nick_name
     *
     * @mbg.generated Fri Mar 29 11:59:24 CST 2019
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.img_url
     *
     * @return the value of admin_user.img_url
     *
     * @mbg.generated Fri Mar 29 11:59:24 CST 2019
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.img_url
     *
     * @param imgUrl the value for admin_user.img_url
     *
     * @mbg.generated Fri Mar 29 11:59:24 CST 2019
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.create_time
     *
     * @return the value of admin_user.create_time
     *
     * @mbg.generated Fri Mar 29 11:59:24 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.create_time
     *
     * @param createTime the value for admin_user.create_time
     *
     * @mbg.generated Fri Mar 29 11:59:24 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.update_time
     *
     * @return the value of admin_user.update_time
     *
     * @mbg.generated Fri Mar 29 11:59:24 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.update_time
     *
     * @param updateTime the value for admin_user.update_time
     *
     * @mbg.generated Fri Mar 29 11:59:24 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.user_status
     *
     * @return the value of admin_user.user_status
     *
     * @mbg.generated Fri Mar 29 11:59:24 CST 2019
     */
    public Integer getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.user_status
     *
     * @param userStatus the value for admin_user.user_status
     *
     * @mbg.generated Fri Mar 29 11:59:24 CST 2019
     */
    public void setUserStatus(Integer userStatus) {
        this.userStatus = userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.user_phone
     *
     * @return the value of admin_user.user_phone
     *
     * @mbg.generated Fri Mar 29 11:59:24 CST 2019
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.user_phone
     *
     * @param userPhone the value for admin_user.user_phone
     *
     * @mbg.generated Fri Mar 29 11:59:24 CST 2019
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.user_email
     *
     * @return the value of admin_user.user_email
     *
     * @mbg.generated Fri Mar 29 11:59:24 CST 2019
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.user_email
     *
     * @param userEmail the value for admin_user.user_email
     *
     * @mbg.generated Fri Mar 29 11:59:24 CST 2019
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail == null ? null : userEmail.trim();
    }
}