package com.simon.cloud.leaf.api.entity;

import java.util.Date;

public class AppGoodsTag {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_goods_tag.id
     *
     * @mbg.generated Thu Apr 18 10:22:38 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_goods_tag.tag_name
     *
     * @mbg.generated Thu Apr 18 10:22:38 CST 2019
     */
    private String tagName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_goods_tag.tag_color
     *
     * @mbg.generated Thu Apr 18 10:22:38 CST 2019
     */
    private String tagColor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_goods_tag.create_time
     *
     * @mbg.generated Thu Apr 18 10:22:38 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_goods_tag.update_time
     *
     * @mbg.generated Thu Apr 18 10:22:38 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_goods_tag.tag_status
     *
     * @mbg.generated Thu Apr 18 10:22:38 CST 2019
     */
    private Integer tagStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_goods_tag.store_id
     *
     * @mbg.generated Thu Apr 18 10:22:38 CST 2019
     */
    private Long storeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_goods_tag.id
     *
     * @return the value of app_goods_tag.id
     *
     * @mbg.generated Thu Apr 18 10:22:38 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_goods_tag.id
     *
     * @param id the value for app_goods_tag.id
     *
     * @mbg.generated Thu Apr 18 10:22:38 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_goods_tag.tag_name
     *
     * @return the value of app_goods_tag.tag_name
     *
     * @mbg.generated Thu Apr 18 10:22:38 CST 2019
     */
    public String getTagName() {
        return tagName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_goods_tag.tag_name
     *
     * @param tagName the value for app_goods_tag.tag_name
     *
     * @mbg.generated Thu Apr 18 10:22:38 CST 2019
     */
    public void setTagName(String tagName) {
        this.tagName = tagName == null ? null : tagName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_goods_tag.tag_color
     *
     * @return the value of app_goods_tag.tag_color
     *
     * @mbg.generated Thu Apr 18 10:22:38 CST 2019
     */
    public String getTagColor() {
        return tagColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_goods_tag.tag_color
     *
     * @param tagColor the value for app_goods_tag.tag_color
     *
     * @mbg.generated Thu Apr 18 10:22:38 CST 2019
     */
    public void setTagColor(String tagColor) {
        this.tagColor = tagColor == null ? null : tagColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_goods_tag.create_time
     *
     * @return the value of app_goods_tag.create_time
     *
     * @mbg.generated Thu Apr 18 10:22:38 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_goods_tag.create_time
     *
     * @param createTime the value for app_goods_tag.create_time
     *
     * @mbg.generated Thu Apr 18 10:22:38 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_goods_tag.update_time
     *
     * @return the value of app_goods_tag.update_time
     *
     * @mbg.generated Thu Apr 18 10:22:38 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_goods_tag.update_time
     *
     * @param updateTime the value for app_goods_tag.update_time
     *
     * @mbg.generated Thu Apr 18 10:22:38 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_goods_tag.tag_status
     *
     * @return the value of app_goods_tag.tag_status
     *
     * @mbg.generated Thu Apr 18 10:22:38 CST 2019
     */
    public Integer getTagStatus() {
        return tagStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_goods_tag.tag_status
     *
     * @param tagStatus the value for app_goods_tag.tag_status
     *
     * @mbg.generated Thu Apr 18 10:22:38 CST 2019
     */
    public void setTagStatus(Integer tagStatus) {
        this.tagStatus = tagStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_goods_tag.store_id
     *
     * @return the value of app_goods_tag.store_id
     *
     * @mbg.generated Thu Apr 18 10:22:38 CST 2019
     */
    public Long getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_goods_tag.store_id
     *
     * @param storeId the value for app_goods_tag.store_id
     *
     * @mbg.generated Thu Apr 18 10:22:38 CST 2019
     */
    public void setStoreId(Long storeId) {
        this.storeId = storeId;
    }
}