package com.simon.cloud.leaf.api.entity;

import java.util.Date;

public class AppGoodsCategory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_goods_category.id
     *
     * @mbg.generated Wed Apr 17 10:51:10 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_goods_category.category_name
     *
     * @mbg.generated Wed Apr 17 10:51:10 CST 2019
     */
    private String categoryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_goods_category.menu_id
     *
     * @mbg.generated Wed Apr 17 10:51:10 CST 2019
     */
    private Long menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_goods_category.category_status
     *
     * @mbg.generated Wed Apr 17 10:51:10 CST 2019
     */
    private Integer categoryStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_goods_category.create_time
     *
     * @mbg.generated Wed Apr 17 10:51:10 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_goods_category.update_time
     *
     * @mbg.generated Wed Apr 17 10:51:10 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_goods_category.store_id
     *
     * @mbg.generated Wed Apr 17 10:51:10 CST 2019
     */
    private Long storeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_goods_category.id
     *
     * @return the value of app_goods_category.id
     *
     * @mbg.generated Wed Apr 17 10:51:10 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_goods_category.id
     *
     * @param id the value for app_goods_category.id
     *
     * @mbg.generated Wed Apr 17 10:51:10 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_goods_category.category_name
     *
     * @return the value of app_goods_category.category_name
     *
     * @mbg.generated Wed Apr 17 10:51:10 CST 2019
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_goods_category.category_name
     *
     * @param categoryName the value for app_goods_category.category_name
     *
     * @mbg.generated Wed Apr 17 10:51:10 CST 2019
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName == null ? null : categoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_goods_category.menu_id
     *
     * @return the value of app_goods_category.menu_id
     *
     * @mbg.generated Wed Apr 17 10:51:10 CST 2019
     */
    public Long getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_goods_category.menu_id
     *
     * @param menuId the value for app_goods_category.menu_id
     *
     * @mbg.generated Wed Apr 17 10:51:10 CST 2019
     */
    public void setMenuId(Long menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_goods_category.category_status
     *
     * @return the value of app_goods_category.category_status
     *
     * @mbg.generated Wed Apr 17 10:51:10 CST 2019
     */
    public Integer getCategoryStatus() {
        return categoryStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_goods_category.category_status
     *
     * @param categoryStatus the value for app_goods_category.category_status
     *
     * @mbg.generated Wed Apr 17 10:51:10 CST 2019
     */
    public void setCategoryStatus(Integer categoryStatus) {
        this.categoryStatus = categoryStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_goods_category.create_time
     *
     * @return the value of app_goods_category.create_time
     *
     * @mbg.generated Wed Apr 17 10:51:10 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_goods_category.create_time
     *
     * @param createTime the value for app_goods_category.create_time
     *
     * @mbg.generated Wed Apr 17 10:51:10 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_goods_category.update_time
     *
     * @return the value of app_goods_category.update_time
     *
     * @mbg.generated Wed Apr 17 10:51:10 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_goods_category.update_time
     *
     * @param updateTime the value for app_goods_category.update_time
     *
     * @mbg.generated Wed Apr 17 10:51:10 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_goods_category.store_id
     *
     * @return the value of app_goods_category.store_id
     *
     * @mbg.generated Wed Apr 17 10:51:10 CST 2019
     */
    public Long getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_goods_category.store_id
     *
     * @param storeId the value for app_goods_category.store_id
     *
     * @mbg.generated Wed Apr 17 10:51:10 CST 2019
     */
    public void setStoreId(Long storeId) {
        this.storeId = storeId;
    }
}