package com.simon.cloud.leaf.api.entity;

import java.util.Date;

public class AppGoodsUnit {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_goods_unit.id
     *
     * @mbg.generated Wed Apr 17 10:28:54 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_goods_unit.unit_name
     *
     * @mbg.generated Wed Apr 17 10:28:54 CST 2019
     */
    private String unitName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_goods_unit.create_time
     *
     * @mbg.generated Wed Apr 17 10:28:54 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_goods_unit.update_time
     *
     * @mbg.generated Wed Apr 17 10:28:54 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_goods_unit.store_id
     *
     * @mbg.generated Wed Apr 17 10:28:54 CST 2019
     */
    private Long storeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_goods_unit.unit_status
     *
     * @mbg.generated Wed Apr 17 10:28:54 CST 2019
     */
    private Integer unitStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_goods_unit.id
     *
     * @return the value of app_goods_unit.id
     *
     * @mbg.generated Wed Apr 17 10:28:54 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_goods_unit.id
     *
     * @param id the value for app_goods_unit.id
     *
     * @mbg.generated Wed Apr 17 10:28:54 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_goods_unit.unit_name
     *
     * @return the value of app_goods_unit.unit_name
     *
     * @mbg.generated Wed Apr 17 10:28:54 CST 2019
     */
    public String getUnitName() {
        return unitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_goods_unit.unit_name
     *
     * @param unitName the value for app_goods_unit.unit_name
     *
     * @mbg.generated Wed Apr 17 10:28:54 CST 2019
     */
    public void setUnitName(String unitName) {
        this.unitName = unitName == null ? null : unitName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_goods_unit.create_time
     *
     * @return the value of app_goods_unit.create_time
     *
     * @mbg.generated Wed Apr 17 10:28:54 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_goods_unit.create_time
     *
     * @param createTime the value for app_goods_unit.create_time
     *
     * @mbg.generated Wed Apr 17 10:28:54 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_goods_unit.update_time
     *
     * @return the value of app_goods_unit.update_time
     *
     * @mbg.generated Wed Apr 17 10:28:54 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_goods_unit.update_time
     *
     * @param updateTime the value for app_goods_unit.update_time
     *
     * @mbg.generated Wed Apr 17 10:28:54 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_goods_unit.store_id
     *
     * @return the value of app_goods_unit.store_id
     *
     * @mbg.generated Wed Apr 17 10:28:54 CST 2019
     */
    public Long getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_goods_unit.store_id
     *
     * @param storeId the value for app_goods_unit.store_id
     *
     * @mbg.generated Wed Apr 17 10:28:54 CST 2019
     */
    public void setStoreId(Long storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_goods_unit.unit_status
     *
     * @return the value of app_goods_unit.unit_status
     *
     * @mbg.generated Wed Apr 17 10:28:54 CST 2019
     */
    public Integer getUnitStatus() {
        return unitStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_goods_unit.unit_status
     *
     * @param unitStatus the value for app_goods_unit.unit_status
     *
     * @mbg.generated Wed Apr 17 10:28:54 CST 2019
     */
    public void setUnitStatus(Integer unitStatus) {
        this.unitStatus = unitStatus;
    }
}