package com.simon.cloud.leaf.api.entity;

public class AppGoodsWithBLOBs extends AppGoods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_goods.goods_pic
     *
     * @mbg.generated Tue Apr 23 21:22:33 CST 2019
     */
    private String goodsPic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_goods.goods_taste
     *
     * @mbg.generated Tue Apr 23 21:22:33 CST 2019
     */
    private String goodsTaste;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_goods.goods_sale_time
     *
     * @mbg.generated Tue Apr 23 21:22:33 CST 2019
     */
    private String goodsSaleTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_goods.goods_pic
     *
     * @return the value of app_goods.goods_pic
     *
     * @mbg.generated Tue Apr 23 21:22:33 CST 2019
     */
    public String getGoodsPic() {
        return goodsPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_goods.goods_pic
     *
     * @param goodsPic the value for app_goods.goods_pic
     *
     * @mbg.generated Tue Apr 23 21:22:33 CST 2019
     */
    public void setGoodsPic(String goodsPic) {
        this.goodsPic = goodsPic == null ? null : goodsPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_goods.goods_taste
     *
     * @return the value of app_goods.goods_taste
     *
     * @mbg.generated Tue Apr 23 21:22:33 CST 2019
     */
    public String getGoodsTaste() {
        return goodsTaste;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_goods.goods_taste
     *
     * @param goodsTaste the value for app_goods.goods_taste
     *
     * @mbg.generated Tue Apr 23 21:22:33 CST 2019
     */
    public void setGoodsTaste(String goodsTaste) {
        this.goodsTaste = goodsTaste == null ? null : goodsTaste.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_goods.goods_sale_time
     *
     * @return the value of app_goods.goods_sale_time
     *
     * @mbg.generated Tue Apr 23 21:22:33 CST 2019
     */
    public String getGoodsSaleTime() {
        return goodsSaleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_goods.goods_sale_time
     *
     * @param goodsSaleTime the value for app_goods.goods_sale_time
     *
     * @mbg.generated Tue Apr 23 21:22:33 CST 2019
     */
    public void setGoodsSaleTime(String goodsSaleTime) {
        this.goodsSaleTime = goodsSaleTime == null ? null : goodsSaleTime.trim();
    }
}