package com.simon.cloud.leaf.api.entity;

import java.util.Date;

public class AppGoods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_goods.id
     *
     * @mbg.generated Tue Apr 23 15:29:37 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_goods.goods_name
     *
     * @mbg.generated Tue Apr 23 15:29:37 CST 2019
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_goods.goods_price
     *
     * @mbg.generated Tue Apr 23 15:29:37 CST 2019
     */
    private Long goodsPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_goods.goods_status
     *
     * @mbg.generated Tue Apr 23 15:29:37 CST 2019
     */
    private Integer goodsStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_goods.create_time
     *
     * @mbg.generated Tue Apr 23 15:29:37 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_goods.update_time
     *
     * @mbg.generated Tue Apr 23 15:29:37 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_goods.category_id
     *
     * @mbg.generated Tue Apr 23 15:29:37 CST 2019
     */
    private Long categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_goods.goods_index
     *
     * @mbg.generated Tue Apr 23 15:29:37 CST 2019
     */
    private Integer goodsIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_goods.unit_id
     *
     * @mbg.generated Tue Apr 23 15:29:37 CST 2019
     */
    private Long unitId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_goods.is_vip
     *
     * @mbg.generated Tue Apr 23 15:29:37 CST 2019
     */
    private Integer isVip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_goods.vip_price
     *
     * @mbg.generated Tue Apr 23 15:29:37 CST 2019
     */
    private Long vipPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_goods.spelling
     *
     * @mbg.generated Tue Apr 23 15:29:37 CST 2019
     */
    private String spelling;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_goods.store_id
     *
     * @mbg.generated Tue Apr 23 15:29:37 CST 2019
     */
    private Long storeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_goods.can_discount
     *
     * @mbg.generated Tue Apr 23 15:29:37 CST 2019
     */
    private Integer canDiscount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_goods.goods_pic
     *
     * @mbg.generated Tue Apr 23 15:29:37 CST 2019
     */
    private String goodsPic;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_goods.id
     *
     * @return the value of app_goods.id
     *
     * @mbg.generated Tue Apr 23 15:29:37 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_goods.id
     *
     * @param id the value for app_goods.id
     *
     * @mbg.generated Tue Apr 23 15:29:37 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_goods.goods_name
     *
     * @return the value of app_goods.goods_name
     *
     * @mbg.generated Tue Apr 23 15:29:37 CST 2019
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_goods.goods_name
     *
     * @param goodsName the value for app_goods.goods_name
     *
     * @mbg.generated Tue Apr 23 15:29:37 CST 2019
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_goods.goods_price
     *
     * @return the value of app_goods.goods_price
     *
     * @mbg.generated Tue Apr 23 15:29:37 CST 2019
     */
    public Long getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_goods.goods_price
     *
     * @param goodsPrice the value for app_goods.goods_price
     *
     * @mbg.generated Tue Apr 23 15:29:37 CST 2019
     */
    public void setGoodsPrice(Long goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_goods.goods_status
     *
     * @return the value of app_goods.goods_status
     *
     * @mbg.generated Tue Apr 23 15:29:37 CST 2019
     */
    public Integer getGoodsStatus() {
        return goodsStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_goods.goods_status
     *
     * @param goodsStatus the value for app_goods.goods_status
     *
     * @mbg.generated Tue Apr 23 15:29:37 CST 2019
     */
    public void setGoodsStatus(Integer goodsStatus) {
        this.goodsStatus = goodsStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_goods.create_time
     *
     * @return the value of app_goods.create_time
     *
     * @mbg.generated Tue Apr 23 15:29:37 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_goods.create_time
     *
     * @param createTime the value for app_goods.create_time
     *
     * @mbg.generated Tue Apr 23 15:29:37 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_goods.update_time
     *
     * @return the value of app_goods.update_time
     *
     * @mbg.generated Tue Apr 23 15:29:37 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_goods.update_time
     *
     * @param updateTime the value for app_goods.update_time
     *
     * @mbg.generated Tue Apr 23 15:29:37 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_goods.category_id
     *
     * @return the value of app_goods.category_id
     *
     * @mbg.generated Tue Apr 23 15:29:37 CST 2019
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_goods.category_id
     *
     * @param categoryId the value for app_goods.category_id
     *
     * @mbg.generated Tue Apr 23 15:29:37 CST 2019
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_goods.goods_index
     *
     * @return the value of app_goods.goods_index
     *
     * @mbg.generated Tue Apr 23 15:29:37 CST 2019
     */
    public Integer getGoodsIndex() {
        return goodsIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_goods.goods_index
     *
     * @param goodsIndex the value for app_goods.goods_index
     *
     * @mbg.generated Tue Apr 23 15:29:37 CST 2019
     */
    public void setGoodsIndex(Integer goodsIndex) {
        this.goodsIndex = goodsIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_goods.unit_id
     *
     * @return the value of app_goods.unit_id
     *
     * @mbg.generated Tue Apr 23 15:29:37 CST 2019
     */
    public Long getUnitId() {
        return unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_goods.unit_id
     *
     * @param unitId the value for app_goods.unit_id
     *
     * @mbg.generated Tue Apr 23 15:29:37 CST 2019
     */
    public void setUnitId(Long unitId) {
        this.unitId = unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_goods.is_vip
     *
     * @return the value of app_goods.is_vip
     *
     * @mbg.generated Tue Apr 23 15:29:37 CST 2019
     */
    public Integer getIsVip() {
        return isVip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_goods.is_vip
     *
     * @param isVip the value for app_goods.is_vip
     *
     * @mbg.generated Tue Apr 23 15:29:37 CST 2019
     */
    public void setIsVip(Integer isVip) {
        this.isVip = isVip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_goods.vip_price
     *
     * @return the value of app_goods.vip_price
     *
     * @mbg.generated Tue Apr 23 15:29:37 CST 2019
     */
    public Long getVipPrice() {
        return vipPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_goods.vip_price
     *
     * @param vipPrice the value for app_goods.vip_price
     *
     * @mbg.generated Tue Apr 23 15:29:37 CST 2019
     */
    public void setVipPrice(Long vipPrice) {
        this.vipPrice = vipPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_goods.spelling
     *
     * @return the value of app_goods.spelling
     *
     * @mbg.generated Tue Apr 23 15:29:37 CST 2019
     */
    public String getSpelling() {
        return spelling;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_goods.spelling
     *
     * @param spelling the value for app_goods.spelling
     *
     * @mbg.generated Tue Apr 23 15:29:37 CST 2019
     */
    public void setSpelling(String spelling) {
        this.spelling = spelling == null ? null : spelling.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_goods.store_id
     *
     * @return the value of app_goods.store_id
     *
     * @mbg.generated Tue Apr 23 15:29:37 CST 2019
     */
    public Long getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_goods.store_id
     *
     * @param storeId the value for app_goods.store_id
     *
     * @mbg.generated Tue Apr 23 15:29:37 CST 2019
     */
    public void setStoreId(Long storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_goods.can_discount
     *
     * @return the value of app_goods.can_discount
     *
     * @mbg.generated Tue Apr 23 15:29:37 CST 2019
     */
    public Integer getCanDiscount() {
        return canDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_goods.can_discount
     *
     * @param canDiscount the value for app_goods.can_discount
     *
     * @mbg.generated Tue Apr 23 15:29:37 CST 2019
     */
    public void setCanDiscount(Integer canDiscount) {
        this.canDiscount = canDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_goods.goods_pic
     *
     * @return the value of app_goods.goods_pic
     *
     * @mbg.generated Tue Apr 23 15:29:37 CST 2019
     */
    public String getGoodsPic() {
        return goodsPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_goods.goods_pic
     *
     * @param goodsPic the value for app_goods.goods_pic
     *
     * @mbg.generated Tue Apr 23 15:29:37 CST 2019
     */
    public void setGoodsPic(String goodsPic) {
        this.goodsPic = goodsPic == null ? null : goodsPic.trim();
    }
}