package com.simon.cloud.leaf.api.entity;

import java.util.Date;

public class AppGoodsTaste {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_goods_taste.id
     *
     * @mbg.generated Wed Apr 24 12:30:50 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_goods_taste.taste_name
     *
     * @mbg.generated Wed Apr 24 12:30:50 CST 2019
     */
    private String tasteName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_goods_taste.store_id
     *
     * @mbg.generated Wed Apr 24 12:30:50 CST 2019
     */
    private Long storeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_goods_taste.create_time
     *
     * @mbg.generated Wed Apr 24 12:30:50 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_goods_taste.update_time
     *
     * @mbg.generated Wed Apr 24 12:30:50 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_goods_taste.taste_status
     *
     * @mbg.generated Wed Apr 24 12:30:50 CST 2019
     */
    private Integer tasteStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_goods_taste.id
     *
     * @return the value of app_goods_taste.id
     *
     * @mbg.generated Wed Apr 24 12:30:50 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_goods_taste.id
     *
     * @param id the value for app_goods_taste.id
     *
     * @mbg.generated Wed Apr 24 12:30:50 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_goods_taste.taste_name
     *
     * @return the value of app_goods_taste.taste_name
     *
     * @mbg.generated Wed Apr 24 12:30:50 CST 2019
     */
    public String getTasteName() {
        return tasteName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_goods_taste.taste_name
     *
     * @param tasteName the value for app_goods_taste.taste_name
     *
     * @mbg.generated Wed Apr 24 12:30:50 CST 2019
     */
    public void setTasteName(String tasteName) {
        this.tasteName = tasteName == null ? null : tasteName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_goods_taste.store_id
     *
     * @return the value of app_goods_taste.store_id
     *
     * @mbg.generated Wed Apr 24 12:30:50 CST 2019
     */
    public Long getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_goods_taste.store_id
     *
     * @param storeId the value for app_goods_taste.store_id
     *
     * @mbg.generated Wed Apr 24 12:30:50 CST 2019
     */
    public void setStoreId(Long storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_goods_taste.create_time
     *
     * @return the value of app_goods_taste.create_time
     *
     * @mbg.generated Wed Apr 24 12:30:50 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_goods_taste.create_time
     *
     * @param createTime the value for app_goods_taste.create_time
     *
     * @mbg.generated Wed Apr 24 12:30:50 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_goods_taste.update_time
     *
     * @return the value of app_goods_taste.update_time
     *
     * @mbg.generated Wed Apr 24 12:30:50 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_goods_taste.update_time
     *
     * @param updateTime the value for app_goods_taste.update_time
     *
     * @mbg.generated Wed Apr 24 12:30:50 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_goods_taste.taste_status
     *
     * @return the value of app_goods_taste.taste_status
     *
     * @mbg.generated Wed Apr 24 12:30:50 CST 2019
     */
    public Integer getTasteStatus() {
        return tasteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_goods_taste.taste_status
     *
     * @param tasteStatus the value for app_goods_taste.taste_status
     *
     * @mbg.generated Wed Apr 24 12:30:50 CST 2019
     */
    public void setTasteStatus(Integer tasteStatus) {
        this.tasteStatus = tasteStatus;
    }
}