package com.simon.cloud.leaf.api.entity;

import java.util.Date;

public class AppMenu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_menu.id
     *
     * @mbg.generated Wed Apr 17 10:23:23 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_menu.menu_name
     *
     * @mbg.generated Wed Apr 17 10:23:23 CST 2019
     */
    private String menuName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_menu.menu_status
     *
     * @mbg.generated Wed Apr 17 10:23:23 CST 2019
     */
    private Integer menuStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_menu.create_time
     *
     * @mbg.generated Wed Apr 17 10:23:23 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_menu.update_time
     *
     * @mbg.generated Wed Apr 17 10:23:23 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_menu.store_id
     *
     * @mbg.generated Wed Apr 17 10:23:23 CST 2019
     */
    private Long storeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_menu.id
     *
     * @return the value of app_menu.id
     *
     * @mbg.generated Wed Apr 17 10:23:23 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_menu.id
     *
     * @param id the value for app_menu.id
     *
     * @mbg.generated Wed Apr 17 10:23:23 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_menu.menu_name
     *
     * @return the value of app_menu.menu_name
     *
     * @mbg.generated Wed Apr 17 10:23:23 CST 2019
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_menu.menu_name
     *
     * @param menuName the value for app_menu.menu_name
     *
     * @mbg.generated Wed Apr 17 10:23:23 CST 2019
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName == null ? null : menuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_menu.menu_status
     *
     * @return the value of app_menu.menu_status
     *
     * @mbg.generated Wed Apr 17 10:23:23 CST 2019
     */
    public Integer getMenuStatus() {
        return menuStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_menu.menu_status
     *
     * @param menuStatus the value for app_menu.menu_status
     *
     * @mbg.generated Wed Apr 17 10:23:23 CST 2019
     */
    public void setMenuStatus(Integer menuStatus) {
        this.menuStatus = menuStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_menu.create_time
     *
     * @return the value of app_menu.create_time
     *
     * @mbg.generated Wed Apr 17 10:23:23 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_menu.create_time
     *
     * @param createTime the value for app_menu.create_time
     *
     * @mbg.generated Wed Apr 17 10:23:23 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_menu.update_time
     *
     * @return the value of app_menu.update_time
     *
     * @mbg.generated Wed Apr 17 10:23:23 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_menu.update_time
     *
     * @param updateTime the value for app_menu.update_time
     *
     * @mbg.generated Wed Apr 17 10:23:23 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_menu.store_id
     *
     * @return the value of app_menu.store_id
     *
     * @mbg.generated Wed Apr 17 10:23:23 CST 2019
     */
    public Long getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_menu.store_id
     *
     * @param storeId the value for app_menu.store_id
     *
     * @mbg.generated Wed Apr 17 10:23:23 CST 2019
     */
    public void setStoreId(Long storeId) {
        this.storeId = storeId;
    }
}