package com.simon.cloud.leaf.api.entity;

import java.util.Date;

public class AppSaleTime {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_sale_time.id
     *
     * @mbg.generated Thu Apr 18 10:36:38 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_sale_time.store_id
     *
     * @mbg.generated Thu Apr 18 10:36:38 CST 2019
     */
    private Long storeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_sale_time.sale_time_name
     *
     * @mbg.generated Thu Apr 18 10:36:38 CST 2019
     */
    private String saleTimeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_sale_time.start_time
     *
     * @mbg.generated Thu Apr 18 10:36:38 CST 2019
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_sale_time.end_time
     *
     * @mbg.generated Thu Apr 18 10:36:38 CST 2019
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_sale_time.create_time
     *
     * @mbg.generated Thu Apr 18 10:36:38 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_sale_time.update_time
     *
     * @mbg.generated Thu Apr 18 10:36:38 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_sale_time.sale_time_status
     *
     * @mbg.generated Thu Apr 18 10:36:38 CST 2019
     */
    private Integer saleTimeStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_sale_time.id
     *
     * @return the value of app_sale_time.id
     *
     * @mbg.generated Thu Apr 18 10:36:38 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_sale_time.id
     *
     * @param id the value for app_sale_time.id
     *
     * @mbg.generated Thu Apr 18 10:36:38 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_sale_time.store_id
     *
     * @return the value of app_sale_time.store_id
     *
     * @mbg.generated Thu Apr 18 10:36:38 CST 2019
     */
    public Long getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_sale_time.store_id
     *
     * @param storeId the value for app_sale_time.store_id
     *
     * @mbg.generated Thu Apr 18 10:36:38 CST 2019
     */
    public void setStoreId(Long storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_sale_time.sale_time_name
     *
     * @return the value of app_sale_time.sale_time_name
     *
     * @mbg.generated Thu Apr 18 10:36:38 CST 2019
     */
    public String getSaleTimeName() {
        return saleTimeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_sale_time.sale_time_name
     *
     * @param saleTimeName the value for app_sale_time.sale_time_name
     *
     * @mbg.generated Thu Apr 18 10:36:38 CST 2019
     */
    public void setSaleTimeName(String saleTimeName) {
        this.saleTimeName = saleTimeName == null ? null : saleTimeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_sale_time.start_time
     *
     * @return the value of app_sale_time.start_time
     *
     * @mbg.generated Thu Apr 18 10:36:38 CST 2019
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_sale_time.start_time
     *
     * @param startTime the value for app_sale_time.start_time
     *
     * @mbg.generated Thu Apr 18 10:36:38 CST 2019
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_sale_time.end_time
     *
     * @return the value of app_sale_time.end_time
     *
     * @mbg.generated Thu Apr 18 10:36:38 CST 2019
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_sale_time.end_time
     *
     * @param endTime the value for app_sale_time.end_time
     *
     * @mbg.generated Thu Apr 18 10:36:38 CST 2019
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_sale_time.create_time
     *
     * @return the value of app_sale_time.create_time
     *
     * @mbg.generated Thu Apr 18 10:36:38 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_sale_time.create_time
     *
     * @param createTime the value for app_sale_time.create_time
     *
     * @mbg.generated Thu Apr 18 10:36:38 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_sale_time.update_time
     *
     * @return the value of app_sale_time.update_time
     *
     * @mbg.generated Thu Apr 18 10:36:38 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_sale_time.update_time
     *
     * @param updateTime the value for app_sale_time.update_time
     *
     * @mbg.generated Thu Apr 18 10:36:38 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_sale_time.sale_time_status
     *
     * @return the value of app_sale_time.sale_time_status
     *
     * @mbg.generated Thu Apr 18 10:36:38 CST 2019
     */
    public Integer getSaleTimeStatus() {
        return saleTimeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_sale_time.sale_time_status
     *
     * @param saleTimeStatus the value for app_sale_time.sale_time_status
     *
     * @mbg.generated Thu Apr 18 10:36:38 CST 2019
     */
    public void setSaleTimeStatus(Integer saleTimeStatus) {
        this.saleTimeStatus = saleTimeStatus;
    }
}