package com.simon.cloud.leaf.provider.dao;

import com.simon.cloud.leaf.api.entity.AdminStore;
import com.simon.cloud.leaf.api.entity.AdminStoreExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdminStoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_store
     *
     * @mbg.generated Thu Apr 18 10:47:46 CST 2019
     */
    long countByExample(AdminStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_store
     *
     * @mbg.generated Thu Apr 18 10:47:46 CST 2019
     */
    int deleteByExample(AdminStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_store
     *
     * @mbg.generated Thu Apr 18 10:47:46 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_store
     *
     * @mbg.generated Thu Apr 18 10:47:46 CST 2019
     */
    int insert(AdminStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_store
     *
     * @mbg.generated Thu Apr 18 10:47:46 CST 2019
     */
    int insertSelective(AdminStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_store
     *
     * @mbg.generated Thu Apr 18 10:47:46 CST 2019
     */
    List<AdminStore> selectByExample(AdminStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_store
     *
     * @mbg.generated Thu Apr 18 10:47:46 CST 2019
     */
    AdminStore selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_store
     *
     * @mbg.generated Thu Apr 18 10:47:46 CST 2019
     */
    int updateByExampleSelective(@Param("record") AdminStore record, @Param("example") AdminStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_store
     *
     * @mbg.generated Thu Apr 18 10:47:46 CST 2019
     */
    int updateByExample(@Param("record") AdminStore record, @Param("example") AdminStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_store
     *
     * @mbg.generated Thu Apr 18 10:47:46 CST 2019
     */
    int updateByPrimaryKeySelective(AdminStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_store
     *
     * @mbg.generated Thu Apr 18 10:47:46 CST 2019
     */
    int updateByPrimaryKey(AdminStore record);
}