package com.simon.cloud.leaf.provider.dao;

import com.simon.cloud.leaf.api.entity.AppGoodsUnit;
import com.simon.cloud.leaf.api.entity.AppGoodsUnitExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface AppGoodsUnitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_unit
     *
     * @mbg.generated Wed Apr 17 10:28:54 CST 2019
     */
    long countByExample(AppGoodsUnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_unit
     *
     * @mbg.generated Wed Apr 17 10:28:54 CST 2019
     */
    int deleteByExample(AppGoodsUnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_unit
     *
     * @mbg.generated Wed Apr 17 10:28:54 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_unit
     *
     * @mbg.generated Wed Apr 17 10:28:54 CST 2019
     */
    int insert(AppGoodsUnit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_unit
     *
     * @mbg.generated Wed Apr 17 10:28:54 CST 2019
     */
    int insertSelective(AppGoodsUnit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_unit
     *
     * @mbg.generated Wed Apr 17 10:28:54 CST 2019
     */
    List<AppGoodsUnit> selectByExample(AppGoodsUnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_unit
     *
     * @mbg.generated Wed Apr 17 10:28:54 CST 2019
     */
    AppGoodsUnit selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_unit
     *
     * @mbg.generated Wed Apr 17 10:28:54 CST 2019
     */
    int updateByExampleSelective(@Param("record") AppGoodsUnit record, @Param("example") AppGoodsUnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_unit
     *
     * @mbg.generated Wed Apr 17 10:28:54 CST 2019
     */
    int updateByExample(@Param("record") AppGoodsUnit record, @Param("example") AppGoodsUnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_unit
     *
     * @mbg.generated Wed Apr 17 10:28:54 CST 2019
     */
    int updateByPrimaryKeySelective(AppGoodsUnit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_unit
     *
     * @mbg.generated Wed Apr 17 10:28:54 CST 2019
     */
    int updateByPrimaryKey(AppGoodsUnit record);
}