package com.simon.cloud.leaf.provider.dao;

import com.simon.cloud.leaf.api.entity.AppGoodsSaleTimeRelation;
import com.simon.cloud.leaf.api.entity.AppGoodsSaleTimeRelationExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface AppGoodsSaleTimeRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_sale_time_relation
     *
     * @mbg.generated Tue Apr 23 15:33:50 CST 2019
     */
    long countByExample(AppGoodsSaleTimeRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_sale_time_relation
     *
     * @mbg.generated Tue Apr 23 15:33:50 CST 2019
     */
    int deleteByExample(AppGoodsSaleTimeRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_sale_time_relation
     *
     * @mbg.generated Tue Apr 23 15:33:50 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_sale_time_relation
     *
     * @mbg.generated Tue Apr 23 15:33:50 CST 2019
     */
    int insert(AppGoodsSaleTimeRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_sale_time_relation
     *
     * @mbg.generated Tue Apr 23 15:33:50 CST 2019
     */
    int insertSelective(AppGoodsSaleTimeRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_sale_time_relation
     *
     * @mbg.generated Tue Apr 23 15:33:50 CST 2019
     */
    List<AppGoodsSaleTimeRelation> selectByExample(AppGoodsSaleTimeRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_sale_time_relation
     *
     * @mbg.generated Tue Apr 23 15:33:50 CST 2019
     */
    AppGoodsSaleTimeRelation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_sale_time_relation
     *
     * @mbg.generated Tue Apr 23 15:33:50 CST 2019
     */
    int updateByExampleSelective(@Param("record") AppGoodsSaleTimeRelation record, @Param("example") AppGoodsSaleTimeRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_sale_time_relation
     *
     * @mbg.generated Tue Apr 23 15:33:50 CST 2019
     */
    int updateByExample(@Param("record") AppGoodsSaleTimeRelation record, @Param("example") AppGoodsSaleTimeRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_sale_time_relation
     *
     * @mbg.generated Tue Apr 23 15:33:50 CST 2019
     */
    int updateByPrimaryKeySelective(AppGoodsSaleTimeRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_sale_time_relation
     *
     * @mbg.generated Tue Apr 23 15:33:50 CST 2019
     */
    int updateByPrimaryKey(AppGoodsSaleTimeRelation record);
}