package com.simon.cloud.leaf.provider.dao;

import com.simon.cloud.leaf.api.entity.AppGoodsTagRelation;
import com.simon.cloud.leaf.api.entity.AppGoodsTagRelationExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface AppGoodsTagRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_tag_relation
     *
     * @mbg.generated Thu Apr 18 10:33:57 CST 2019
     */
    long countByExample(AppGoodsTagRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_tag_relation
     *
     * @mbg.generated Thu Apr 18 10:33:57 CST 2019
     */
    int deleteByExample(AppGoodsTagRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_tag_relation
     *
     * @mbg.generated Thu Apr 18 10:33:57 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_tag_relation
     *
     * @mbg.generated Thu Apr 18 10:33:57 CST 2019
     */
    int insert(AppGoodsTagRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_tag_relation
     *
     * @mbg.generated Thu Apr 18 10:33:57 CST 2019
     */
    int insertSelective(AppGoodsTagRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_tag_relation
     *
     * @mbg.generated Thu Apr 18 10:33:57 CST 2019
     */
    List<AppGoodsTagRelation> selectByExample(AppGoodsTagRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_tag_relation
     *
     * @mbg.generated Thu Apr 18 10:33:57 CST 2019
     */
    AppGoodsTagRelation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_tag_relation
     *
     * @mbg.generated Thu Apr 18 10:33:57 CST 2019
     */
    int updateByExampleSelective(@Param("record") AppGoodsTagRelation record, @Param("example") AppGoodsTagRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_tag_relation
     *
     * @mbg.generated Thu Apr 18 10:33:57 CST 2019
     */
    int updateByExample(@Param("record") AppGoodsTagRelation record, @Param("example") AppGoodsTagRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_tag_relation
     *
     * @mbg.generated Thu Apr 18 10:33:57 CST 2019
     */
    int updateByPrimaryKeySelective(AppGoodsTagRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_tag_relation
     *
     * @mbg.generated Thu Apr 18 10:33:57 CST 2019
     */
    int updateByPrimaryKey(AppGoodsTagRelation record);
}