package com.simon.cloud.leaf.provider.dao;

import com.simon.cloud.leaf.api.entity.AppGoodsTaste;
import com.simon.cloud.leaf.api.entity.AppGoodsTasteExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface AppGoodsTasteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_taste
     *
     * @mbg.generated Wed Apr 17 14:18:50 CST 2019
     */
    long countByExample(AppGoodsTasteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_taste
     *
     * @mbg.generated Wed Apr 17 14:18:50 CST 2019
     */
    int deleteByExample(AppGoodsTasteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_taste
     *
     * @mbg.generated Wed Apr 17 14:18:50 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_taste
     *
     * @mbg.generated Wed Apr 17 14:18:50 CST 2019
     */
    int insert(AppGoodsTaste record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_taste
     *
     * @mbg.generated Wed Apr 17 14:18:50 CST 2019
     */
    int insertSelective(AppGoodsTaste record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_taste
     *
     * @mbg.generated Wed Apr 17 14:18:50 CST 2019
     */
    List<AppGoodsTaste> selectByExampleWithBLOBs(AppGoodsTasteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_taste
     *
     * @mbg.generated Wed Apr 17 14:18:50 CST 2019
     */
    List<AppGoodsTaste> selectByExample(AppGoodsTasteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_taste
     *
     * @mbg.generated Wed Apr 17 14:18:50 CST 2019
     */
    AppGoodsTaste selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_taste
     *
     * @mbg.generated Wed Apr 17 14:18:50 CST 2019
     */
    int updateByExampleSelective(@Param("record") AppGoodsTaste record, @Param("example") AppGoodsTasteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_taste
     *
     * @mbg.generated Wed Apr 17 14:18:50 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") AppGoodsTaste record, @Param("example") AppGoodsTasteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_taste
     *
     * @mbg.generated Wed Apr 17 14:18:50 CST 2019
     */
    int updateByExample(@Param("record") AppGoodsTaste record, @Param("example") AppGoodsTasteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_taste
     *
     * @mbg.generated Wed Apr 17 14:18:50 CST 2019
     */
    int updateByPrimaryKeySelective(AppGoodsTaste record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_taste
     *
     * @mbg.generated Wed Apr 17 14:18:50 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(AppGoodsTaste record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_taste
     *
     * @mbg.generated Wed Apr 17 14:18:50 CST 2019
     */
    int updateByPrimaryKey(AppGoodsTaste record);
}