package com.simon.cloud.leaf.provider.dao;

import com.simon.cloud.leaf.api.entity.AppGoodsCategory;
import com.simon.cloud.leaf.api.entity.AppGoodsCategoryExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface AppGoodsCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_category
     *
     * @mbg.generated Wed Apr 17 10:51:10 CST 2019
     */
    long countByExample(AppGoodsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_category
     *
     * @mbg.generated Wed Apr 17 10:51:10 CST 2019
     */
    int deleteByExample(AppGoodsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_category
     *
     * @mbg.generated Wed Apr 17 10:51:10 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_category
     *
     * @mbg.generated Wed Apr 17 10:51:10 CST 2019
     */
    int insert(AppGoodsCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_category
     *
     * @mbg.generated Wed Apr 17 10:51:10 CST 2019
     */
    int insertSelective(AppGoodsCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_category
     *
     * @mbg.generated Wed Apr 17 10:51:10 CST 2019
     */
    List<AppGoodsCategory> selectByExample(AppGoodsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_category
     *
     * @mbg.generated Wed Apr 17 10:51:10 CST 2019
     */
    AppGoodsCategory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_category
     *
     * @mbg.generated Wed Apr 17 10:51:10 CST 2019
     */
    int updateByExampleSelective(@Param("record") AppGoodsCategory record, @Param("example") AppGoodsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_category
     *
     * @mbg.generated Wed Apr 17 10:51:10 CST 2019
     */
    int updateByExample(@Param("record") AppGoodsCategory record, @Param("example") AppGoodsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_category
     *
     * @mbg.generated Wed Apr 17 10:51:10 CST 2019
     */
    int updateByPrimaryKeySelective(AppGoodsCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_category
     *
     * @mbg.generated Wed Apr 17 10:51:10 CST 2019
     */
    int updateByPrimaryKey(AppGoodsCategory record);
}