package com.simon.cloud.leaf.provider.dao;

import com.simon.cloud.leaf.api.entity.AppGoodsTag;
import com.simon.cloud.leaf.api.entity.AppGoodsTagExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface AppGoodsTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_tag
     *
     * @mbg.generated Thu Apr 18 10:22:38 CST 2019
     */
    long countByExample(AppGoodsTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_tag
     *
     * @mbg.generated Thu Apr 18 10:22:38 CST 2019
     */
    int deleteByExample(AppGoodsTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_tag
     *
     * @mbg.generated Thu Apr 18 10:22:38 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_tag
     *
     * @mbg.generated Thu Apr 18 10:22:38 CST 2019
     */
    int insert(AppGoodsTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_tag
     *
     * @mbg.generated Thu Apr 18 10:22:38 CST 2019
     */
    int insertSelective(AppGoodsTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_tag
     *
     * @mbg.generated Thu Apr 18 10:22:38 CST 2019
     */
    List<AppGoodsTag> selectByExample(AppGoodsTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_tag
     *
     * @mbg.generated Thu Apr 18 10:22:38 CST 2019
     */
    AppGoodsTag selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_tag
     *
     * @mbg.generated Thu Apr 18 10:22:38 CST 2019
     */
    int updateByExampleSelective(@Param("record") AppGoodsTag record, @Param("example") AppGoodsTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_tag
     *
     * @mbg.generated Thu Apr 18 10:22:38 CST 2019
     */
    int updateByExample(@Param("record") AppGoodsTag record, @Param("example") AppGoodsTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_tag
     *
     * @mbg.generated Thu Apr 18 10:22:38 CST 2019
     */
    int updateByPrimaryKeySelective(AppGoodsTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_tag
     *
     * @mbg.generated Thu Apr 18 10:22:38 CST 2019
     */
    int updateByPrimaryKey(AppGoodsTag record);
}