package com.simon.cloud.leaf.provider.dao;

import com.simon.cloud.leaf.api.entity.AppGoodsTasteRelation;
import com.simon.cloud.leaf.api.entity.AppGoodsTasteRelationExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface AppGoodsTasteRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_taste_relation
     *
     * @mbg.generated Tue Apr 23 15:32:46 CST 2019
     */
    long countByExample(AppGoodsTasteRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_taste_relation
     *
     * @mbg.generated Tue Apr 23 15:32:46 CST 2019
     */
    int deleteByExample(AppGoodsTasteRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_taste_relation
     *
     * @mbg.generated Tue Apr 23 15:32:46 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_taste_relation
     *
     * @mbg.generated Tue Apr 23 15:32:46 CST 2019
     */
    int insert(AppGoodsTasteRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_taste_relation
     *
     * @mbg.generated Tue Apr 23 15:32:46 CST 2019
     */
    int insertSelective(AppGoodsTasteRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_taste_relation
     *
     * @mbg.generated Tue Apr 23 15:32:46 CST 2019
     */
    List<AppGoodsTasteRelation> selectByExample(AppGoodsTasteRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_taste_relation
     *
     * @mbg.generated Tue Apr 23 15:32:46 CST 2019
     */
    AppGoodsTasteRelation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_taste_relation
     *
     * @mbg.generated Tue Apr 23 15:32:46 CST 2019
     */
    int updateByExampleSelective(@Param("record") AppGoodsTasteRelation record, @Param("example") AppGoodsTasteRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_taste_relation
     *
     * @mbg.generated Tue Apr 23 15:32:46 CST 2019
     */
    int updateByExample(@Param("record") AppGoodsTasteRelation record, @Param("example") AppGoodsTasteRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_taste_relation
     *
     * @mbg.generated Tue Apr 23 15:32:46 CST 2019
     */
    int updateByPrimaryKeySelective(AppGoodsTasteRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_goods_taste_relation
     *
     * @mbg.generated Tue Apr 23 15:32:46 CST 2019
     */
    int updateByPrimaryKey(AppGoodsTasteRelation record);
}