package com.simon.cloud.leaf.provider.dao;

import com.simon.cloud.leaf.api.entity.AppMenu;
import com.simon.cloud.leaf.api.entity.AppMenuExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface AppMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_menu
     *
     * @mbg.generated Wed Apr 17 10:23:23 CST 2019
     */
    long countByExample(AppMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_menu
     *
     * @mbg.generated Wed Apr 17 10:23:23 CST 2019
     */
    int deleteByExample(AppMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_menu
     *
     * @mbg.generated Wed Apr 17 10:23:23 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_menu
     *
     * @mbg.generated Wed Apr 17 10:23:23 CST 2019
     */
    int insert(AppMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_menu
     *
     * @mbg.generated Wed Apr 17 10:23:23 CST 2019
     */
    int insertSelective(AppMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_menu
     *
     * @mbg.generated Wed Apr 17 10:23:23 CST 2019
     */
    List<AppMenu> selectByExample(AppMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_menu
     *
     * @mbg.generated Wed Apr 17 10:23:23 CST 2019
     */
    AppMenu selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_menu
     *
     * @mbg.generated Wed Apr 17 10:23:23 CST 2019
     */
    int updateByExampleSelective(@Param("record") AppMenu record, @Param("example") AppMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_menu
     *
     * @mbg.generated Wed Apr 17 10:23:23 CST 2019
     */
    int updateByExample(@Param("record") AppMenu record, @Param("example") AppMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_menu
     *
     * @mbg.generated Wed Apr 17 10:23:23 CST 2019
     */
    int updateByPrimaryKeySelective(AppMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_menu
     *
     * @mbg.generated Wed Apr 17 10:23:23 CST 2019
     */
    int updateByPrimaryKey(AppMenu record);
}