package com.simon.cloud.leaf.provider.dao;

import com.simon.cloud.leaf.api.entity.AppSaleTime;
import com.simon.cloud.leaf.api.entity.AppSaleTimeExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface AppSaleTimeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_sale_time
     *
     * @mbg.generated Tue Apr 23 19:49:28 CST 2019
     */
    long countByExample(AppSaleTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_sale_time
     *
     * @mbg.generated Tue Apr 23 19:49:28 CST 2019
     */
    int deleteByExample(AppSaleTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_sale_time
     *
     * @mbg.generated Tue Apr 23 19:49:28 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_sale_time
     *
     * @mbg.generated Tue Apr 23 19:49:28 CST 2019
     */
    int insert(AppSaleTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_sale_time
     *
     * @mbg.generated Tue Apr 23 19:49:28 CST 2019
     */
    int insertSelective(AppSaleTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_sale_time
     *
     * @mbg.generated Tue Apr 23 19:49:28 CST 2019
     */
    List<AppSaleTime> selectByExample(AppSaleTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_sale_time
     *
     * @mbg.generated Tue Apr 23 19:49:28 CST 2019
     */
    AppSaleTime selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_sale_time
     *
     * @mbg.generated Tue Apr 23 19:49:28 CST 2019
     */
    int updateByExampleSelective(@Param("record") AppSaleTime record, @Param("example") AppSaleTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_sale_time
     *
     * @mbg.generated Tue Apr 23 19:49:28 CST 2019
     */
    int updateByExample(@Param("record") AppSaleTime record, @Param("example") AppSaleTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_sale_time
     *
     * @mbg.generated Tue Apr 23 19:49:28 CST 2019
     */
    int updateByPrimaryKeySelective(AppSaleTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_sale_time
     *
     * @mbg.generated Tue Apr 23 19:49:28 CST 2019
     */
    int updateByPrimaryKey(AppSaleTime record);
}